version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBAPI_PORT:-5000}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD:-YourStrong!Password}"
      ACCEPT_EULA: "Y"
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD:-YourStrong!Password}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  api_network:
