# docker-compose.yml for Clean Architecture
version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBAPI_PORT:-5000}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    secrets:
      - sa_password
    depends_on:
      - database
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "/run/secrets/sa_password", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    secrets:
      - sa_password
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1G"

volumes:
  db_data:

networks:
  api_network:

secrets:
  sa_password:
    file: ./secrets/sa_password.txt
